import { Elements } from '../interfaces/elements';

export const elements: Elements = {
    buttonElement: {
        parentId: '',
        id: '',
        nameid: '',
        type: 'Button',
        label: 'Button',
        left: 15,
        top: 15,
        maxWidth: 100,
        lineClamp: 1,
        color: '#efefef',
        fontColor: '#000000',
        isVisible: true,
        isEnabled: true,
        onClick: 'run',
        elementIds: [],
        conditions: ''
    },
    inputElement: {
        parentId: '',
        type: 'Input',
        id: '',
        nameid: '',
        width: 120,
        left: 15,
        top: 15,
        isVisible: true,
        isEnabled: true,
        value: '',
        elementIds: [],
        conditions: ''
    },
    selectElement: {
        parentId: '',
        type: 'Select',
        id: '',
        nameid: '',
        width: 120,
        left: 15,
        top: 15,
        // dataSource: 'custom', // too R specific
        // Robjects: 'all',      // too R specific
        value: '',
        isVisible: true,
        isEnabled: true,
        elementIds: [],
        conditions: ''
    },
    checkboxElement: {
        parentId: '',
        type: 'Checkbox',
        id: '',
        nameid: '',
        left: 10,
        top: 10,
        size: 14,
        color: '#4caf50',
        isChecked: false,
        isVisible: true,
        isEnabled: true,
        elementIds: [],
        conditions: ''
    },
    radioElement: {
        parentId: '',
        type: 'Radio',
        id: '',
        group: 'radiogroup1',
        left: 10,
        top: 10,
        size: 14,
        color: '#4caf50',
        isSelected: false,
        isVisible: true,
        isEnabled: true,
        elementIds: [],
        conditions: ''
    },
    counterElement: {
        parentId: '',
        type: 'Counter',
        id: '',
        nameid: '',
        startval: 1,
        maxval: 5,
        space: 4,
        left: 15,
        top: 15,
        color: '#4caf50',
        isVisible: true,
        isEnabled: true,
        elementIds: [],
        conditions: ''
    },
    sliderElement: {
        parentId: '',
        type: 'Slider',
        id: '',
        nameid: '',
        handlepos: 50,
        handleshape: 'triangle',
        handlecolor: '#4caf50',
        handlesize: 8,
        width: 120,
        height: 1,
        left: 15,
        top: 15,
        direction: "horizontal",
        color: "#000000",
        isVisible: true,
        isEnabled: true,
        elementIds: [],
        conditions: ''
    },
    labelElement: {
        parentId: '',
        type: 'Label',
        id: '',
        fontColor: '#000000',
        left: 15,
        top: 15,
        maxWidth: 200,
        isVisible: true,
        value: 'Label',
        elementIds: [],
        conditions: ''
    },
    separatorElement: {
        parentId: '',
        type: 'Separator',
        id: '',
        width: 200,
        height: 1,
        left: 15,
        top: 15,
        direction: "horizontal",
        color: "#000000",
        isVisible: true,
        elementIds: [],
        conditions: ''
    },
    containerElement: {
        parentId: '',
        type: 'Container',
        id: '',
        nameid: '',
        objViewClass: 'variable',
        variableType: '',
        parentContainer: '',
        width: 150,
        height: 200,
        left: 15,
        top: 15,
        isVisible: true,
        isEnabled: true,
        elementIds: [],
        conditions: ''
    }
}
