name: test-sign

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sign:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Check Azure secrets are present
        shell: pwsh
        run: |
          if ("${{ secrets.AZURE_APPLICATION_ID }}" -eq "") { throw "AZURE_APPLICATION_ID is empty" }
          if ("${{ secrets.AZURE_TENANT_ID }}" -eq "") { throw "AZURE_TENANT_ID is empty" }
          if ("${{ secrets.AZURE_SUBSCRIPTION_ID }}" -eq "") { throw "AZURE_SUBSCRIPTION_ID is empty" }
          Write-Host "All Azure secrets are present"

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_APPLICATION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign
        uses: azure/artifact-signing-action@v1
        with:
          endpoint: https://neu.codesigning.azure.net/
          signing-account-name: dusadrian
          certificate-profile-name: electron-profile
          files-folder: ${{ github.workspace }}
          files-folder-filter: exe